// <auto-generated />
using KampusApp.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KampusApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210126074449_AddAkademikToDb")]
    partial class AddAkademikToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KampusApp.Model.Akademik", b =>
                {
                    b.Property<int>("IDAkademik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDMatakuliah")
                        .HasColumnType("int");

                    b.Property<int>("NIM")
                        .HasColumnType("int");

                    b.Property<string>("NamaMahasiswa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaMatakuliah")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDAkademik");

                    b.ToTable("Akademik");
                });

            modelBuilder.Entity("KampusApp.Model.Mahasiswa", b =>
                {
                    b.Property<int>("NIM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NIM");

                    b.ToTable("Mahasiswa");
                });

            modelBuilder.Entity("KampusApp.Model.Matakuliah", b =>
                {
                    b.Property<int>("IDMatakuliah")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaMatakuliah")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SKS")
                        .HasColumnType("int");

                    b.HasKey("IDMatakuliah");

                    b.ToTable("Matakuliah");
                });
#pragma warning restore 612, 618
        }
    }
}
